matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.3
# before_install:
#   - carthage bootstrap --verbose
script:
  - set -o pipefail
  - xcodebuild test -scheme Barrel-Mac -configuration Debug | xcpretty -c
  - xcodebuild test -scheme Barrel-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty -c
  - xcodebuild test -scheme Barrel-tvOS -configuration Debug -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c
  - xcodebuild build -scheme Barrel-watchOS -configuration Debug -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" | xcpretty -c
